### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by zkimyes** [ghmcadams/vscode-lintlens#34] opened 2020-12-08 00:33 UTC
- Issue Type: `Bug`
- Extension Name: `lintlens`
- Extension Version: `3.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ghmcadams** [comment] 2020-12-08 01:05
@zkimyes, It appears that there was supposed to be some data for you to paste, but I see none.  Could you please paste it here?


Thank you,
Gabriel

**Comment by jerone** [comment] 2021-01-30 12:55
This is my report, but i doubt it's useful:

*   Issue Type: `Bug`
*   Extension Name: `lintlens`
*   Extension Version: `3.0.0`
*   OS Version: `Windows_NT x64 10.0.19042`
*   VSCode version: `1.52.1`

```json
{
    "messages": [],
    "activationTimes": {
        "codeLoadingTime": 17439,
        "activateCallTime": 0,
        "activateResolvedTime": 715,
        "activationReason": {
            "startup": true,
            "extensionId": {
                "value": "ghmcadams.lintlens",
                "_lower": "ghmcadams.lintlens"
            },
            "activationEvent": "workspaceContainsTimeout:**/.eslintrc*,**/package.json"
        }
    },
    "runtimeErrors": []
}
```

**Comment by ghmcadams** [comment] 2021-02-01 17:56
@zkimyes and @jerone I am not sure what the issue is?  Could you please provide some information about the bug?  Expected vs actual would be helpful.  What you were doing when it happened.  Anything that can tell me what I am looking for and what is going on.

Thank you,
Gabriel

**Comment by jerone** [comment] 2021-02-01 18:00
These kind of reports are generated when opening VSCode. So, I'm not doing anything, VSCode is just loading extensions and configurations.

What I do find interesting is the activation event; does that exclude `node_modules` folder?

**Comment by ghmcadams** [comment] 2021-02-02 17:41
@jerone unfortunately, there is nothing I can do at this time.  The description of an issue is missing and the report does not tell me much of anything.  I am closing this for now.  Please open a new issue if you notice anything specific and actionable.

Thank you,
Gabriel

**Closed as completed by ghmcadams** 2021-02-02 17:41 UTC
