### ISSUE TITLE
Updating to TypeScript ESLint v6 shows plugin missing

### ISSUE THREAD

**Issue by TrevorSayre** [ghmcadams/vscode-lintlens#72] opened 2023-07-22 21:45 UTC
After updating to [TypeScript ESLint v6](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/), all the "@typescript-eslint" rules say:

```
Plugin missing "@typescript-eslint/eslint-plugin"
```

<img width="723" alt="image" src="https://github.com/ghmcadams/vscode-lintlens/assets/421548/d8804230-7772-4918-acce-d27a94925d20">

using:
```
"@typescript-eslint/eslint-plugin": "^6.1.0",
"@typescript-eslint/parser": "^6.1.0",
```
and:
```
"eslint": "^8.45.0",
"eslint-config-prettier": "^8.8.0",
```

**Comment by ghmcadams** [comment] 2023-07-23 01:03
I can look into this, but can you do me a favor and restart vscode and tell me if that solves this?

**Comment by ghmcadams** [comment] 2023-07-23 18:41
After investigating, I found that this is caused by the `@typescript-eslint/eslint-plugin` package no longer including `main` in their `package.json` file.  I filed [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/7300) and [this PR](https://github.com/typescript-eslint/typescript-eslint/pull/7301) to resolve this.  Waiting...

**Comment by Eejit43** [comment] 2023-07-26 20:29
> After investigating, I found that this is caused by the `@typescript-eslint/eslint-plugin` package no longer including `main` in their `package.json` file. I filed [this issue](https://github.com/typescript-eslint/typescript-eslint/issues/7300) and [this PR](https://github.com/typescript-eslint/typescript-eslint/pull/7301) to resolve this. Waiting...

I'm a little confused by all the jargon used in that issue and PR, do you expect there will be any way around this? Thanks for the amazing extension!

**Comment by ghmcadams** [comment] 2023-07-27 02:43
I published a fix for this issue a couple of minutes ago.  There is sometimes a delay but it should be available to you soon.  Please let me know if you have any further issues.

**Closed as completed by ghmcadams** 2023-07-27 02:43 UTC

**Comment by Eejit43** [comment] 2023-07-27 11:54
> I published a fix for this issue a couple of minutes ago. There is sometimes a delay but it should be available to you soon. Please let me know if you have any further issues.

thank you so much!!
